apiVersion: batch/v1
kind: CronJob
metadata:
  name: temperature-scraper
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: scraper
              image: 717279705656.dkr.ecr.us-east-1.amazonaws.com/temp-scraper:latest
              imagePullPolicy: IfNotPresent
              env:
                - name: KAFKA_BROKERS
                  value: "kafka.kafka.svc.cluster.local:9092"
          restartPolicy: OnFailure